version: '3.9'

services:
    client:
        container_name: mean-jwt-client
        build: mean-jwt-client
        ports:
            - "4200:4200"
        volumes:
            - ./mean-jwt-client:/app
    api:
        container_name: mean-jwt-api
        build: mean-jwt-api
        command: npm run dev
        ports:
            - "3000:3000"
        volumes:
            - ./mean-jwt-api:/usr/src/app
        links:
            - database
    database:
        image: mongo:latest
#        environment:
#            - MONGO_INITDB_ROOT_USERNAME=devroot
#            - MONGO_INITDB_ROOT_PASSWORD=devroot
#            - MONGO_INITDB_DATABASE=meanjwt
        ports:
            - "27017:27017"
        container_name: mean-jwt-database
        volumes:
            - shared_database:/data/db
volumes:
    shared_database:

